{{- if .Values.s3 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "triton-inference-server.fullname" . }}-s3-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "triton-inference-server.name" . }}
    chart: {{ template "triton-inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }} 
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.s3.creds.s3AccessKey }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3.creds.s3SecretKey }}"
  AWS_DEFAULT_REGION: "{{ .Values.s3.creds.s3Zone }}"
{{- end }}
